// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmghXN3Q_vX40zizLqAijuD8J7SWCmcq4',
    appId: '1:355916344297:web:4941b241672b8efdfbb978',
    messagingSenderId: '355916344297',
    projectId: 'arista-232bf',
    authDomain: 'arista-232bf.firebaseapp.com',
    storageBucket: 'arista-232bf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSRlAMdED5NAozaQZTj1PLoYyjk3tH3zk',
    appId: '1:355916344297:android:a01171969283b427fbb978',
    messagingSenderId: '355916344297',
    projectId: 'arista-232bf',
    storageBucket: 'arista-232bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiE8_vta36a8SfwuVTKnPURlI9I03Vy2I',
    appId: '1:355916344297:ios:0e20aaafe7ade64cfbb978',
    messagingSenderId: '355916344297',
    projectId: 'arista-232bf',
    storageBucket: 'arista-232bf.appspot.com',
    iosClientId: '355916344297-60e0h89vp8j7cp4q3tjs0drlp1udph0d.apps.googleusercontent.com',
    iosBundleId: 'com.example.arista',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiE8_vta36a8SfwuVTKnPURlI9I03Vy2I',
    appId: '1:355916344297:ios:0e20aaafe7ade64cfbb978',
    messagingSenderId: '355916344297',
    projectId: 'arista-232bf',
    storageBucket: 'arista-232bf.appspot.com',
    iosClientId: '355916344297-60e0h89vp8j7cp4q3tjs0drlp1udph0d.apps.googleusercontent.com',
    iosBundleId: 'com.example.arista',
  );
}
